@extends('layouts.app')
@section('title','Home')

@section('content')
  {{-- Banner Section (image from public/assets/images/it.webp) --}}
    <!-- Banner Section -->
    <section class="banner-section">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="banner-content">
                        <h1 class="banner-title">Unlock Your Potential with EduLearn</h1>
                        <p class="banner-text">Join thousands of students who have transformed their careers with our industry-leading courses and expert instructors.</p>
                        <div class="banner-buttons">
                            <a href="courses.html" class="btn btn-primary-custom me-3">Explore Courses</a>
                            <a href="#" class="btn btn-secondary-custom">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="banner-img">
                        <img src="./assets/images/it.webp" alt="Banner Image" class="img-fluid">
                </div>
            </div>
        </div>
    </section>

    <!-- Courses Section -->
    <section class="py-5">
        <div class="container">
        <div class="section-header">
            <h1>Our Popular Courses</h1>
            <div class="divider"></div>
            <p>Choose from a wide range of professional courses designed to boost your career</p>
        </div>

        <div class="courses-slider">
            <div class="courses-container" id="coursesContainer">
                <!-- Course 1 -->
                 @forelse ($popularCourses as $index => $course)
            @php
                $thumb = $course->thumbnail ? asset('storage/' . ltrim($course->thumbnail, '/')) : asset('images/default-course.jpg');
            @endphp
            <div class="course-card">
                    <div class="course-header">
                        <div class="course-brand">
                            <div class="course-number">{{ $index + 1 }}</div>
                            <h3 class="course-title text-white">{{ $course->title }}</h3>
                        </div>
                    </div>
                    <div class="course-content">
                        
                        <div class="course-details text-center">
                             <img src="{{ $thumb }}" alt="{{ $course->title }}" class="img-fluid mb-2" style="max-height:90px;object-fit:contain;">
                        </div>
                        <p class="course-description"> {!! \Illuminate\Support\Str::limit(strip_tags($course->excerpt ?? $course->description), 120) !!}</p>
                        <a href="{{ route('courses.details', $course->slug) }}" class="btn-view-details">View Details</a>
                    </div>
                </div>
        @empty
            <div class="swiper-slide text-center">
                <p class="text-muted">No courses found.</p>
            </div>
        @endforelse

                

                <!-- Additional Courses for Slider -->
              
               
               
            </div>

            <div class="slider-nav">
                <div class="nav-btn" id="prevBtn">
                    <i class="fas fa-chevron-left"></i>
                </div>
                
                <div class="slider-dots" id="sliderDots">
                    <!-- Dots will be generated by JavaScript -->
                </div>
                
                <div class="nav-btn" id="nextBtn">
                    <i class="fas fa-chevron-right"></i>
                </div>
                
                <button class="btn-view-all">View All Courses</button>
            </div>
        </div>
    </div>
    </section>

    <!-- Call to Action Section -->
    <section class="cta-section">
        <div class="container">
            <h2 class="cta-title">Ready to Transform Your Career?</h2>
            <p class="cta-text">Join our community of learners and take the first step towards achieving your professional goals with our expert-led courses.</p>
            <a href="#" class="btn btn-primary-custom me-3">Enroll Now</a>
            <a href="about.html" class="btn btn-light">Learn More</a>
        </div>
    </section>

    <!-- Blog Section -->
    <section class="py-5 bg-light">
        <div class="container">
            <h2 class="section-title">Latest from Our Blog</h2>
            <p class="section-subtitle">Stay updated with the latest trends, tips, and insights in education and career development</p>
            
           {{-- ========= Latest from Our Blog (3 latest) ========= --}}
<div class="row g-4">
    @forelse ($latestBlogs as $blog)
        @php
            $blogUrl   = url('/blog/' . $blog->slug);  // adjust if you have a named route
            $blogThumb = !empty($blog->thumbnail) ? asset('storage/' . ltrim($blog->thumbnail, '/')) : null;
        @endphp

        <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100 shadow-sm border-0 rounded-4">
                @if($blogThumb)
                    <a href="{{ $blogUrl }}">
                        <img src="{{ $blogThumb }}" class="card-img-top" alt="{{ $blog->title }}" style="height:180px;object-fit:cover;">
                    </a>
                @endif
                <div class="card-body">
                    <h6 class="card-title mb-1">
                        <a class="text-decoration-none" href="{{ $blogUrl }}">{{ $blog->title }}</a>
                    </h6>
                    <div class="text-secondary small">
                        {{ \Carbon\Carbon::parse($blog->created_at)->format('M d, Y') }}
                    </div>
                </div>
            </div>
        </div>
    @empty
        <div class="col-12">
            <p class="text-muted mb-0">No blog posts yet.</p>
        </div>
    @endforelse
</div>
            
            <div class="text-center mt-4">
                <a href="blog.html" class="btn btn-outline-primary">View All Blogs</a>
            </div>
        </div>
    </section>

@endsection